import api from './api';
import { Prescription, RouteOfAdministrationEnum } from '@/types/prescription';

export interface CreatePrescriptionItemInput {
  medicationId: string;
  medicationName: string;
  // Structured regimen (NEW)
  strengthPerDose: string;
  dosesPerDay: number;
  durationDays: number;
  /** Total in base units. If 0/missing, backend computes from structured fields. */
  quantity: number;
  // Legacy free-text overrides (auto-generated by backend)
  dosage?: string;
  frequency?: string;
  duration?: string;
  route?: RouteOfAdministrationEnum;
  /** Patient-facing label text. If omitted, backend auto-generates from strengthPerDose+dosesPerDay+durationDays+route */
  instructions?: string;
  /** Internal pharmacist note — not printed on label */
  pharmacistNote?: string;
}

export interface CreatePrescriptionInput {
  patientId: string;
  consultationId?: string;
  visitId?: string;
  doctorId?: string;
  items: CreatePrescriptionItemInput[];
  /** General notes from doctor — visible to pharmacist and patient */
  notes?: string;
  totalAmount?: number;
}

export interface DispenseItemInput {
  medicationId: string;
  dispenseMode: 'individual' | 'pack';
  packSizeIndex?: number;
  sellUnits: number;
  manualSellUnitLabel?: string;
  manualPricePerSellUnit?: number;
  manualBaseUnitsPerSellUnit?: number;
  substituteMedicationId?: string;
  substituteNote?: string;
}

export interface DispenseInput {
  items: DispenseItemInput[];
  dispensingNotes?: string;
  paymentMethod?: string;
}

export const prescriptionService = {
  async create(data: CreatePrescriptionInput): Promise<Prescription> {
    const response = await api.post('/prescriptions', data);
    return response.data;
  },

  async findAll(): Promise<Prescription[]> {
    const response = await api.get('/prescriptions');
    return response.data;
  },

  async findById(id: string): Promise<Prescription> {
    const response = await api.get(`/prescriptions/${id}`);
    return response.data;
  },

  async findByPatient(patientId: string): Promise<Prescription[]> {
    const response = await api.get(`/prescriptions/patient/${patientId}`);
    return response.data;
  },

  async findPendingPayment(): Promise<Prescription[]> {
    const response = await api.get('/prescriptions/pending-payment');
    return response.data;
  },

  async findPendingDispense(): Promise<Prescription[]> {
    const response = await api.get('/prescriptions/pending-dispense');
    return response.data;
  },

  /**
   * Dispense a prescription.
   * @param id prescription id
   * @param input Either a string (legacy: dispensingNotes only) or a full DispenseInput
   *   with per-item dispense records (mode, pack, sellUnits, optional substitute).
   */
  async dispense(id: string, input: string | DispenseInput): Promise<Prescription> {
    const body: DispenseInput = typeof input === 'string' ? { dispensingNotes: input } : input;
    const response = await api.patch(`/prescriptions/${id}/dispense`, body);
    return response.data;
  },

  async markAsPaid(id: string, paymentMethod = 'cash'): Promise<Prescription> {
    const response = await api.patch(`/prescriptions/${id}/mark-paid`, { paymentMethod });
    return response.data;
  },

  async cancel(id: string, reason: string): Promise<Prescription> {
    const response = await api.patch(`/prescriptions/${id}/cancel`, { reason });
    return response.data;
  },

  async update(id: string, data: { items?: CreatePrescriptionItemInput[]; notes?: string; totalAmount?: number }): Promise<Prescription> {
    const response = await api.patch(`/prescriptions/${id}`, data);
    return response.data;
  },

  async getMarWorklist(): Promise<any[]> {
    const response = await api.get('/prescriptions/mar-worklist');
    return response.data;
  },

  async administer(id: string, data: {
    medicationName: string;
    dosage: string;
    route: string;
    given?: boolean;
    refused?: boolean;
    refusalReason?: string;
    notes?: string;
  }): Promise<Prescription> {
    const response = await api.post(`/prescriptions/${id}/administer`, data);
    return response.data;
  },

  async initializeAdmin(id: string): Promise<Prescription> {
    const response = await api.post(`/prescriptions/${id}/initialize-admin`);
    return response.data;
  },
};
